sudo: false

services:
  - postgresql

language: python
python:
  - "3.6"

env:
  - TRAVIS_CI=True

cache:
  apt: true
  yarn: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - node_modules

install:
  - make
before_script:
  - psql -c "CREATE DATABASE test_db_app;" -U postgres
  - psql -c "CREATE USER db_user WITH PASSWORD 'db_pass';" -U postgres
script:
  - make ci
  - make analyze
after_success:
  - codecov
